
import { createClient } from '@supabase/supabase-js';

// Hardcoded credentials to prevent environment variable crashes
const supabaseUrl = 'https://qewwautamhntxeiwpwcr.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFld3dhdXRhbWhudHhlaXdwd2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4NzkwNjEsImV4cCI6MjA4MDQ1NTA2MX0.6JDlwuP06OXZu_bJ4eeC-_177AA50yDm0o_0Nb9uDMc';

if (!supabaseUrl || !supabaseKey) {
  console.error('Supabase credentials missing!');
}

// Export configuration status for App.tsx check
export const isSupabaseConfigured = true;

export const supabase = createClient(supabaseUrl, supabaseKey);

/*
-- DEFINITIVE SQL FIX FOR SOMALIPIN DASHBOARD
-- Run this in your Supabase SQL Editor to enable all Admin Dashboard features.

-- 1. Setup Categories Table
CREATE TABLE IF NOT EXISTS public.archive_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT NOT NULL,
    section_type TEXT CHECK (section_type IN ('POLITICS', 'JUDICIARY', 'SECURITY')) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Populate Standard Categories
INSERT INTO public.archive_categories (category_name, section_type) VALUES 
('Madaxweynayaasha (1960-2022)', 'POLITICS'),
('Ra''iisul Wasaarayaasha', 'POLITICS'),
('Baarlamaanka', 'POLITICS'),
('Golaha Wasiirada', 'POLITICS'),
('Maxkamadaha & Garsoorayaasha', 'JUDICIARY'),
('Qareennada', 'JUDICIARY'),
('Ciidanka Xoogga Dalka (SNA)', 'SECURITY'),
('Ciidanka Booliska (SPF)', 'SECURITY'),
('Nabadsugidda & Asluubta', 'SECURITY')
ON CONFLICT DO NOTHING;

-- 3. Setup Assignments Table
CREATE TABLE IF NOT EXISTS public.archive_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.dossiers(id) ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES public.archive_categories(id) ON DELETE CASCADE,
    start_date TEXT,
    end_date TEXT,
    title_note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. SECURITY POLICIES (RLS) - This is the fix for "Violates Row-Level Security"
ALTER TABLE public.dossiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.archive_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.archive_assignments ENABLE ROW LEVEL SECURITY;

-- Allow anonymous users to manage dossiers (Required for Admin Login simulation)
DROP POLICY IF EXISTS "Admin Management for Dossiers" ON public.dossiers;
CREATE POLICY "Admin Management for Dossiers" ON public.dossiers FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- Allow anonymous users to manage categories
DROP POLICY IF EXISTS "Admin Management for Categories" ON public.archive_categories;
CREATE POLICY "Admin Management for Categories" ON public.archive_categories FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

-- Allow anonymous users to manage assignments
DROP POLICY IF EXISTS "Admin Management for Assignments" ON public.archive_assignments;
CREATE POLICY "Admin Management for Assignments" ON public.archive_assignments FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
*/
