
import { createClient } from '@supabase/supabase-js';

// Hardcoded credentials to prevent environment variable crashes
const supabaseUrl = 'https://qewwautamhntxeiwpwcr.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFld3dhdXRhbWhudHhlaXdwd2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4NzkwNjEsImV4cCI6MjA4MDQ1NTA2MX0.6JDlwuP06OXZu_bJ4eeC-_177AA50yDm0o_0Nb9uDMc';

if (!supabaseUrl || !supabaseKey) {
  console.error('Supabase credentials missing!');
}

// Export configuration status for App.tsx check
export const isSupabaseConfigured = true;

export const supabase = createClient(supabaseUrl, supabaseKey);

/*
-- UPDATED SQL SETUP FOR SOMALIPIN
-- This enables management of Business and Arts & Culture categories.

-- 1. Setup Categories Table with expanded section types
CREATE TABLE IF NOT EXISTS public.archive_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name TEXT NOT NULL,
    section_type TEXT CHECK (section_type IN ('POLITICS', 'JUDICIARY', 'SECURITY', 'BUSINESS', 'ARTS_CULTURE')) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Populate Standard Categories for all Sectors
INSERT INTO public.archive_categories (category_name, section_type) VALUES 
('Madaxweynayaasha (1960-Present)', 'POLITICS'),
('Shirkadaha Isgaarsiinta', 'BUSINESS'),
('Bankiyada & Maaliyadda', 'BUSINESS'),
('Abwaannada & Hal-abuurka', 'ARTS_CULTURE'),
('Fannaaniinta Qaranka', 'ARTS_CULTURE'),
('Hoggaanka SNA', 'SECURITY'),
('Garsoorka Maxkamadda Sare', 'JUDICIARY')
ON CONFLICT DO NOTHING;

-- 3. Setup Assignments Table (Links Profiles to Categories)
CREATE TABLE IF NOT EXISTS public.archive_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.dossiers(id) ON DELETE CASCADE,
    category_id BIGINT NOT NULL REFERENCES public.archive_categories(id) ON DELETE CASCADE,
    start_date TEXT,
    end_date TEXT,
    title_note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Enable Row Level Security
ALTER TABLE public.dossiers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.archive_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.archive_assignments ENABLE ROW LEVEL SECURITY;

-- 5. Policies (Allow Anon for Admin Simulation)
CREATE POLICY "Admin All" ON public.dossiers FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Admin All" ON public.archive_categories FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Admin All" ON public.archive_assignments FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
*/
