
import { createClient } from '@supabase/supabase-js';

// Hardcoded credentials to prevent environment variable crashes
const supabaseUrl = 'https://qewwautamhntxeiwpwcr.supabase.co';
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFld3dhdXRhbWhudHhlaXdwd2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ4NzkwNjEsImV4cCI6MjA4MDQ1NTA2MX0.6JDlwuP06OXZu_bJ4eeC-_177AA50yDm0o_0Nb9uDMc';

if (!supabaseUrl || !supabaseKey) {
  console.error('Supabase credentials missing!');
}

// Export configuration status for App.tsx check
export const isSupabaseConfigured = true;

export const supabase = createClient(supabaseUrl, supabaseKey);

/*
-- ==========================================================
-- COMPLETE MASTER SQL SETUP: RUN THIS TO FIX ALL DB ERRORS
-- ==========================================================
-- Run this in Supabase SQL Editor to ensure all tables exist:

-- 1. Create 'dossiers' table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.dossiers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  full_name text NOT NULL,
  role text,
  bio text,
  status text DEFAULT 'Unverified',
  reputation_score integer DEFAULT 0,
  image_url text,
  category text,
  verification_level text DEFAULT 'Standard',
  details jsonb DEFAULT '{}'::jsonb
);

-- 2. Create 'archive_categories' table
CREATE TABLE IF NOT EXISTS public.archive_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_name text NOT NULL,
  section_type text NOT NULL
);

-- 3. Reset/Update Section Type Constraint
ALTER TABLE public.archive_categories 
DROP CONSTRAINT IF EXISTS archive_categories_section_type_check;

ALTER TABLE public.archive_categories 
ADD CONSTRAINT archive_categories_section_type_check 
CHECK (section_type IN (
  'POLITICS', 'JUDICIARY', 'SECURITY', 'BUSINESS', 
  'ARTS_CULTURE', 'THE_SCHOLARS', 'THE_PIONEERS',
  'PUBLIC_INSTITUTIONS', 'ENTREPRENEURS', 'NGOS'
));

-- 4. Create 'archive_assignments' table for joining
CREATE TABLE IF NOT EXISTS public.archive_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES public.dossiers(id) ON DELETE CASCADE,
  category_id bigint REFERENCES public.archive_categories(id) ON DELETE CASCADE,
  start_date text,
  end_date text,
  title_note text
);

-- 5. Create 'partners' table
CREATE TABLE IF NOT EXISTS public.partners (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  name text NOT NULL,
  logo_url text NOT NULL
);

-- 6. Create 'archive_sectors' table for homepage
CREATE TABLE IF NOT EXISTS public.archive_sectors (
  id text PRIMARY KEY,
  title text NOT NULL,
  description text
);

-- 7. Initialize Home Sectors Metadata
INSERT INTO public.archive_sectors (id, title, description) VALUES 
('business', 'Business (Ganacsiga)', 'Tracking Somali entrepreneurship and corporate pioneers.'),
('arts_culture', 'Arts & Culture', 'Preserving the legacy of Somali artists and custodians.'),
('scholars', 'The Scholars (Aqoonyahanno)', 'Celebrating academic excellence and intellectual contributions.'),
('pioneers', 'The Pioneers', 'Honoring the trailblazers who laid the foundation of the nation.'),
('public_institutions', 'Public Institutions', 'Registry of national agencies, ministries, and state organizations.'),
('entrepreneurs', 'Entrepreneurs', 'Focusing on individual founders and visionary business leaders.'),
('ngos', 'NGOs (Ururada)', 'Highlighting the contributions of Local and International non-governmental organizations.')
ON CONFLICT (id) DO UPDATE SET 
  title = EXCLUDED.title, 
  description = EXCLUDED.description;
*/
